import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import ChakraProvider from "./_providers/ChakraProvider";
import StoreProvider from "./_providers/StoreProvider";
import { theme } from "@/styles/theme";
import AudioPlayer from "../components/AudioPlayer";

const noto_sans_kr = Noto_Sans_KR({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto_sans_kr.className}>
        <ChakraProvider theme={theme}>
          <StoreProvider>{children}</StoreProvider>
        </ChakraProvider>
        <AudioPlayer />
      </body>
    </html>
  );
}
